import Link from "next/link";
import { listOAuth2Clients } from "@/lib/hydra";
import { Pagination } from "@/components/Pagination";
import { currentTenant } from "@/lib/tenant";
import {
  Card,
  EmptyState,
  ErrorState,
  PageHeader,
  Table,
} from "@/components/ui";
import { Flash } from "@/components/forms";
import { CreateClientForm } from "./CreateClientForm";
import { deleteClientAction } from "./actions";

export const dynamic = "force-dynamic";

export default async function OAuthClientsPage({
  searchParams,
}: {
  searchParams: Promise<{
    saved?: string;
    warning?: string;
    error?: string;
    page_token?: string;
  }>;
}) {
  const { page_token, ...flash } = await searchParams;
  const tenant = await currentTenant();
  const result = await listOAuth2Clients(tenant, { pageToken: page_token });

  return (
    <>
      <PageHeader
        title="Clients and applications"
        description="OAuth2 clients let first- and third-party applications obtain tokens from your authorization server."
      />
      <Flash {...flash} />

      <Card title="OAuth2 clients">
        {result.error ? (
          <ErrorState
            message={`Could not reach Hydra admin API: ${result.error}`}
          />
        ) : result.items.length === 0 ? (
          <EmptyState message="It looks like you have no clients yet. Create one below." />
        ) : (
          <Table
            headers={["Name", "Client ID", "Grants", "Auth method", ""]}
          >
            {result.items.map((client) => (
              <tr key={client.client_id} className="hover:bg-canvas">
                <td className="px-3 py-2 font-medium">
                  <Link
                    href={`/oauth/${encodeURIComponent(client.client_id)}`}
                    className="hover:text-accent hover:underline"
                  >
                    {client.client_name || "(unnamed client)"}
                  </Link>
                </td>
                <td className="px-3 py-2 font-mono text-xs text-fg-muted">
                  {client.client_id}
                </td>
                <td className="px-3 py-2 text-xs text-fg-muted">
                  {client.grant_types?.join(", ") ?? "—"}
                </td>
                <td className="px-3 py-2 text-xs text-fg-muted">
                  {client.token_endpoint_auth_method ?? "—"}
                </td>
                <td className="px-3 py-2 text-right">
                  <form action={deleteClientAction}>
                    <input
                      type="hidden"
                      name="client_id"
                      value={client.client_id}
                    />
                    <button
                      type="submit"
                      className="text-sm text-error hover:underline"
                    >
                      Remove
                    </button>
                  </form>
                </td>
              </tr>
            ))}
          </Table>
        )}

        {result.items.length > 0 ? (
          <Pagination
            pageSize={25}
            nextHref={
              result.nextPageToken
                ? `/oauth?page_token=${result.nextPageToken}`
                : null
            }
          />
        ) : null}
      </Card>

      <Card
        title="Create a new client"
        description="The client secret is generated by Hydra and shown only once after creation."
      >
        <CreateClientForm />
      </Card>
    </>
  );
}
